begin;
create extension if not exists pgtap with schema extensions;
select plan(9);
select has_column('public','meter_readings','client_operation_id','meter readings have offline idempotency key');
select has_column('public','receipts','client_operation_id','receipts have offline idempotency key');
select has_column('public','tenants','subscription_expires_at','tenants have subscription expiry');
select has_index('public','meter_readings_client_operation_uidx','meter reading idempotency index exists');
select has_index('public','receipts_client_operation_uidx','receipt idempotency index exists');
select has_index('public','user_roles_one_tenant_role_uidx','one operational account per role per tenant is enforced');
select ok(to_regclass('public.tenant_sustainability_metrics') is not null,'sustainability metrics view exists');
select ok(has_function_privilege('anon','public.admin_manage_tenant(uuid,text,public.subscription_tier)','execute') = false,'anonymous callers cannot manage tenants');
select ok(has_function_privilege('authenticated','public.admin_manage_tenant(uuid,text,public.subscription_tier)','execute'),'authenticated callers reach lifecycle RPC, which self-authorizes super_admin');
select * from finish();
rollback;
