import { createFileRoute, redirect } from "@tanstack/react-router";
import { Shield, Pause, Play, Loader2 } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { AdminUsers } from "@/components/AdminUsers";
import { ProvisionTenantForm } from "@/components/ProvisionTenantForm";

export const Route=createFileRoute("/_authenticated/admin")({head:()=>({meta:[{title:"الإدارة المركزية — منصة ميزان الذكية"}]}),beforeLoad:async()=>{const {data}=await supabase.auth.getUser();if(!data.user)throw redirect({to:"/auth"});const {data:r}=await supabase.from("user_roles").select("role,tenant_id").eq("user_id",data.user.id);if(!r?.some(x=>x.role==="super_admin"&&!x.tenant_id))throw redirect({to:"/dashboard"})},component:AdminPage});
interface Tenant{id:string;name:string;status:"active"|"suspended";subscription_tier:"free"|"premium";tariff_per_m3:number;subscription_started_at:string|null;subscription_expires_at:string|null;created_at:string;}
function AdminPage(){const [tenants,setTenants]=useState<Tenant[]>([]);const [loading,setLoading]=useState(true);const load=async()=>{setLoading(true);const {data,error}=await supabase.from("tenants").select("id,name,status,subscription_tier,tariff_per_m3,subscription_started_at,subscription_expires_at,created_at").order("created_at",{ascending:false});setLoading(false);if(error){toast.error(error.message);return}setTenants((data??[]) as Tenant[])};useEffect(()=>{void load()},[]);
 const action=async(t:Tenant,a:"suspend"|"activate"|"renew")=>{const {error}=await supabase.rpc("admin_manage_tenant",{_tenant_id:t.id,_action:a,_subscription_tier:null});if(error)toast.error(error.message);else{toast.success(a==="renew"?"تم تجديد الاشتراك لمدة سنة":a==="suspend"?"تم تعليق المشروع":"تمت إعادة تفعيل المشروع");void load()}};
 const tier=async(t:Tenant,v:"free"|"premium")=>{const {error}=await supabase.rpc("admin_manage_tenant",{_tenant_id:t.id,_action:"tier",_subscription_tier:v});if(error)toast.error(error.message);else void load()};
 return <div className="space-y-6"><div className="glass rounded-2xl p-6"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl brand-gradient text-white"><Shield className="h-5 w-5"/></div><div><h1 className="text-2xl font-extrabold">الإدارة المركزية</h1><p className="text-sm text-muted-foreground">إدارة دورة حياة مشاريع المياه والاشتراكات والحسابات التشغيلية.</p></div></div></div><ProvisionTenantForm onCreated={()=>void load()}/><div className="glass overflow-hidden rounded-2xl"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/50 text-xs"><tr><th className="p-3 text-right">المشروع</th><th className="p-3">الحالة</th><th className="p-3">الاشتراك</th><th className="p-3">التعرفة</th><th className="p-3">إجراءات</th></tr></thead><tbody>{loading&&<tr><td colSpan={5} className="p-6 text-center text-muted-foreground"><Loader2 className="mx-auto h-5 w-5 animate-spin"/></td></tr>}{!loading&&tenants.length===0&&<tr><td colSpan={5} className="p-6 text-center text-muted-foreground">لا توجد مشاريع</td></tr>}{tenants.map(t=><tr key={t.id} className="border-t border-border"><td className="p-3 text-right font-semibold">{t.name}</td><td className="p-3 text-center"><span className={`rounded-full px-2 py-0.5 text-[11px] font-bold ${t.status==="active"?"bg-emerald-50 text-emerald-700":"bg-rose-50 text-rose-700"}`}>{t.status==="active"?"نشط":"موقوف"}</span></td><td className="p-3 text-center"><div className="flex items-center justify-center gap-2"><select value={t.subscription_tier} onChange={e=>void tier(t,e.target.value as "free"|"premium")} className="rounded-lg border border-border bg-card px-2 py-1 text-xs"><option value="free">مجاني</option><option value="premium">مميز</option></select><span className="text-[10px] text-muted-foreground">{t.subscription_expires_at?new Date(t.subscription_expires_at).toLocaleDateString("ar-YE"):"غير محدد"}</span></div></td><td className="p-3 text-center num">{t.tariff_per_m3}</td><td className="p-3"><div className="flex justify-center gap-2"><button onClick={()=>void action(t,t.status==="active"?"suspend":"activate")} className="inline-flex items-center gap-1 rounded-lg border border-border px-2.5 py-1.5 text-xs font-bold">{t.status==="active"?<><Pause className="h-3 w-3"/>تعليق</>:<><Play className="h-3 w-3"/>تفعيل</>}</button><button onClick={()=>void action(t,"renew")} className="rounded-lg border border-border px-2.5 py-1.5 text-xs font-bold">تجديد سنة</button></div></td></tr>)}</tbody></table></div></div><AdminUsers tenants={tenants.map(t=>({id:t.id,name:t.name}))}/></div>}
