import { useState } from "react";
import { Loader2, UserPlus } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";

const roleFields = [
  ["project_manager", "مدير المشروع"],
  ["meter_reader", "قارئ العدادات"],
  ["financial_collector", "المحصل"],
] as const;

export function ProvisionTenantForm({ onCreated }: { onCreated: () => void }) {
  const [name,setName]=useState(""); const [tariff,setTariff]=useState("250"); const [tier,setTier]=useState("free"); const [busy,setBusy]=useState(false);
  const [accounts,setAccounts]=useState<Record<string,{email:string;password:string;full_name:string}>>({ project_manager:{email:"",password:"",full_name:""}, meter_reader:{email:"",password:"",full_name:""}, financial_collector:{email:"",password:"",full_name:""} });
  const setAccount=(role:string,key:string,value:string)=>setAccounts((current)=>({...current,[role]:{...current[role], [key]:value}}));
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{const {data,error}=await supabase.functions.invoke("admin-provision-tenant",{body:{name,tariff_per_m3:Number(tariff),subscription_tier:tier,accounts:roleFields.map(([role])=>({...accounts[role],role}))}});if(error)throw error;if(data?.error)throw new Error(data.error);toast.success("تم إنشاء مشروع المياه والحسابات الثلاثة");setName("");setTariff("250");setAccounts({ project_manager:{email:"",password:"",full_name:""}, meter_reader:{email:"",password:"",full_name:""}, financial_collector:{email:"",password:"",full_name:""} });onCreated()}catch(error){toast.error(error instanceof Error?error.message:"تعذر إنشاء المشروع")}finally{setBusy(false)}};
  return <form onSubmit={submit} className="glass space-y-5 rounded-2xl p-5"><div className="flex items-center gap-2"><UserPlus className="h-5 w-5"/><div><h2 className="font-bold">إنشاء مشروع مياه وحساباته</h2><p className="text-xs text-muted-foreground">ينشئ النظام مشروعًا واحدًا وثلاثة حسابات تشغيلية مرتبطة به ذريًا.</p></div></div><div className="grid gap-3 sm:grid-cols-3"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="اسم مشروع المياه" className="rounded-lg border border-border bg-card px-3 py-2 text-sm sm:col-span-2"/><input required type="number" min="0" value={tariff} onChange={e=>setTariff(e.target.value)} placeholder="التعرفة / م³" className="rounded-lg border border-border bg-card px-3 py-2 text-sm"/><select value={tier} onChange={e=>setTier(e.target.value)} className="rounded-lg border border-border bg-card px-3 py-2 text-sm"><option value="free">مجاني</option><option value="premium">مميز</option></select></div><div className="grid gap-4 lg:grid-cols-3">{roleFields.map(([role,label])=><fieldset key={role} className="rounded-xl border border-border p-4"><legend className="px-1 text-xs font-bold">{label}</legend><div className="space-y-2"><input required value={accounts[role].full_name} onChange={e=>setAccount(role,"full_name",e.target.value)} placeholder="اسم المستخدم" className="w-full rounded-lg border border-border bg-card px-3 py-2 text-sm"/><input required type="email" value={accounts[role].email} onChange={e=>setAccount(role,"email",e.target.value)} placeholder="البريد الإلكتروني" className="w-full rounded-lg border border-border bg-card px-3 py-2 text-sm"/><input required minLength={8} maxLength={128} type="password" value={accounts[role].password} onChange={e=>setAccount(role,"password",e.target.value)} placeholder="كلمة المرور (8 أحرف+)" className="w-full rounded-lg border border-border bg-card px-3 py-2 text-sm"/></div></fieldset>)}</div><button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-xl brand-gradient px-4 py-3 text-sm font-bold text-white disabled:opacity-60">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<UserPlus className="h-4 w-4"/>}إنشاء المشروع والحسابات</button></form>;
}
