import { useEffect, useState } from "react";
import { Activity, Droplets, Gauge, Wallet } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

interface Metrics { subscribers:number; active_subscribers:number; consumption_m3:number; billed_yer:number; collected_yer:number; outstanding_yer:number; collection_rate_pct:number; }

export function SustainabilityPanel({ tenantId }: { tenantId: string | null }) {
  const [m,setM]=useState<Metrics|null>(null);
  useEffect(()=>{if(!tenantId){setM(null);return;}let alive=true;const load=async()=>{const {data}=await supabase.from("tenant_sustainability_metrics").select("subscribers,active_subscribers,consumption_m3,billed_yer,collected_yer,outstanding_yer,collection_rate_pct").eq("tenant_id",tenantId).maybeSingle();if(alive&&data)setM(data as Metrics)};void load();const ch=supabase.channel(`sustainability-${tenantId}`).on("postgres_changes",{event:"*",schema:"public",table:"billing_logs",filter:`tenant_id=eq.${tenantId}`},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"meter_readings",filter:`tenant_id=eq.${tenantId}`},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"subscribers",filter:`tenant_id=eq.${tenantId}`},()=>void load()).subscribe();return()=>{alive=false;void supabase.removeChannel(ch)}},[tenantId]);
  const collection=Math.max(0,Math.min(100,Number(m?.collection_rate_pct??0))); const activity=m&&m.subscribers?Math.max(0,Math.min(100,(m.active_subscribers/m.subscribers)*100)):0; const score=Math.round(collection*0.6+activity*0.4);
  return <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={Wallet} label="نسبة التحصيل" value={`${collection.toFixed(1)}%`} detail="استدامة مالية"/><Metric icon={Activity} label="مؤشر MIZAN للاستدامة" value={`${score}/100`} detail="60% مالي · 40% تشغيلي"/><Metric icon={Droplets} label="الاستهلاك" value={`${Number(m?.consumption_m3??0).toLocaleString("en-US")} م³`} detail="إجمالي القراءات"/><Metric icon={Gauge} label="المتأخرات" value={`${Number(m?.outstanding_yer??0).toLocaleString("en-US")} ر.ي`} detail="الرصيد غير المحصل"/></div><div className="glass rounded-2xl p-5"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-bold">مؤشرات الاستدامة</h2><p className="text-xs text-muted-foreground">لوحة موحدة لاتخاذ القرار المالي والتشغيلي.</p></div><span className="rounded-full bg-brand-50 px-3 py-1 text-xs font-bold text-brand-700">MIZAN Score {score}/100</span></div><div className="h-3 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full brand-gradient transition-all" style={{width:`${score}%`}}/></div><div className="mt-2 flex justify-between text-[11px] text-muted-foreground"><span>0 — يحتاج تدخل</span><span>100 — مستدام</span></div></div></div>;
}
function Metric({icon:Icon,label,value,detail}:{icon:typeof Wallet;label:string;value:string;detail:string}){return <div className="glass rounded-2xl p-5"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-muted-foreground">{label}</span><div className="grid h-9 w-9 place-items-center rounded-xl brand-gradient text-white"><Icon className="h-4 w-4"/></div></div><div className="num mt-3 text-2xl font-extrabold">{value}</div><div className="mt-1 text-[11px] text-muted-foreground">{detail}</div></div>}
